server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.99.100:49161
    username: dummy
    password: dummy
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml